"""verify_schema_alignment

Revision ID: 6017f3168bcf
Revises: 
Create Date: 2026-10-09 22:33:54.411239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6017f3168bcf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_configurations', 'parameters',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('agent_configurations', 'last_execution_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('agent_configurations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_proposals', 'run_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('agent_proposals', 'expected_benefits',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('agent_proposals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('agent_proposals_run_id_fkey'), 'agent_proposals', type_='foreignkey')
    op.create_foreign_key(None, 'agent_proposals', 'planning_runs', ['run_id'], ['id'])
    op.alter_column('app_users', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('app_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('app_users', 'last_active_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_events', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('constraint_configurations', 'value',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('constraint_configurations', 'unit',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('constraint_configurations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('dataset_versions', 'imported_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint(None, 'dataset_versions', ['version'])
    op.alter_column('distribution_centers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('distribution_centers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('planner_decisions', 'plan_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('planner_decisions', 'run_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('planner_decisions', 'rationale',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('planner_decisions', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('planner_decisions_plan_id_fkey'), 'planner_decisions', type_='foreignkey')
    op.drop_constraint(op.f('planner_decisions_run_id_fkey'), 'planner_decisions', type_='foreignkey')
    op.create_foreign_key(None, 'planner_decisions', 'recovery_plans', ['plan_id'], ['id'])
    op.alter_column('planning_runs', 'scenario_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('planning_runs', 'start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('planning_runs', 'completion_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('planning_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('production_resources', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('production_resources', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('recovery_plans', 'run_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('recovery_plans', 'summary',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('recovery_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('recovery_plans_run_id_fkey'), 'recovery_plans', type_='foreignkey')
    op.create_foreign_key(None, 'recovery_plans', 'planning_runs', ['run_id'], ['id'])
    op.alter_column('scenarios', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('scenarios', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('supplier_products', 'supplier_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('supplier_products', 'product_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_constraint(op.f('supplier_products_product_id_fkey'), 'supplier_products', type_='foreignkey')
    op.drop_constraint(op.f('supplier_products_supplier_id_fkey'), 'supplier_products', type_='foreignkey')
    op.create_foreign_key(None, 'supplier_products', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'supplier_products', 'suppliers', ['supplier_id'], ['id'])
    op.alter_column('suppliers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('suppliers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suppliers', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('suppliers', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'supplier_products', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'supplier_products', type_='foreignkey')
    op.create_foreign_key(op.f('supplier_products_supplier_id_fkey'), 'supplier_products', 'suppliers', ['supplier_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('supplier_products_product_id_fkey'), 'supplier_products', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.alter_column('supplier_products', 'product_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('supplier_products', 'supplier_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('scenarios', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('scenarios', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'recovery_plans', type_='foreignkey')
    op.create_foreign_key(op.f('recovery_plans_run_id_fkey'), 'recovery_plans', 'planning_runs', ['run_id'], ['id'], ondelete='CASCADE')
    op.alter_column('recovery_plans', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('recovery_plans', 'summary',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('recovery_plans', 'run_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('products', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('products', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('production_resources', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('production_resources', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('planning_runs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('planning_runs', 'completion_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('planning_runs', 'start_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('planning_runs', 'scenario_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'planner_decisions', type_='foreignkey')
    op.create_foreign_key(op.f('planner_decisions_run_id_fkey'), 'planner_decisions', 'planning_runs', ['run_id'], ['id'])
    op.create_foreign_key(op.f('planner_decisions_plan_id_fkey'), 'planner_decisions', 'recovery_plans', ['plan_id'], ['id'], ondelete='CASCADE')
    op.alter_column('planner_decisions', 'timestamp',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('planner_decisions', 'rationale',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('planner_decisions', 'run_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('planner_decisions', 'plan_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('distribution_centers', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('distribution_centers', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'dataset_versions', type_='unique')
    op.alter_column('dataset_versions', 'imported_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('constraint_configurations', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('constraint_configurations', 'unit',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('constraint_configurations', 'value',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('audit_events', 'timestamp',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('app_users', 'last_active_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('app_users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('app_users', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'agent_proposals', type_='foreignkey')
    op.create_foreign_key(op.f('agent_proposals_run_id_fkey'), 'agent_proposals', 'planning_runs', ['run_id'], ['id'], ondelete='CASCADE')
    op.alter_column('agent_proposals', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_proposals', 'expected_benefits',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('agent_proposals', 'run_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('agent_configurations', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_configurations', 'last_execution_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('agent_configurations', 'parameters',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    # ### end Alembic commands ###
