import { NextResponse } from 'next/server';
import { query } from '@/lib/db';

export async function GET() {
  try {
    const agents = await query(`
      SELECT * FROM agent_configurations ORDER BY agent_type ASC
    `);

    // Fetch recent proposals generated by each agent
    const recentProposals = await query(`
      SELECT p.*, r.scenario_id, r.strategy
      FROM agent_proposals p
      JOIN planning_runs r ON r.id = p.run_id
      ORDER BY p.created_at DESC LIMIT 20
    `);

    const enriched = agents.map((agent: any) => ({
      ...agent,
      recentProposals: recentProposals.filter(
        (p: any) => p.agent_type === agent.agent_type
      ),
    }));

    return NextResponse.json({ agents: enriched });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
